import random

a = random.randint(1,500)

b = int(input("Enter your number : "))
c = input("select which level you want : EASY LEVEL / HARD LEVEL : ")
    

if( c == "Easy Level"):
    count = 1
    while(count<11):
        if(a==b):
            print(f"Congrats u have found the number : {b}")
            break
        elif(b<a):
            print("the Greater Number than the Generated number")
            print(f"you only had {10-count} chances to solve this problem")
            count+=1
            b = int(input("select your number : "))
        elif(b>a):
            print("the Less Number than the generated number")
            print(f"you only had {10-count} chances to solve this problem")
            count+=1
            b = int(input("select your number : "))
        

elif(c == "Hard Level"):
    count = 1
    while(count<5):
        
    
    
        
        if(a==b):
            print(f"Congrats u have finded the number : {b}")
        elif(b<a):
            print("the Less Number than the generated number")
            print(f"you only had {5-count} chances to solve this problem")
            count+=1
            b = int(input("select your number : "))
        elif(b>a):
            print("the Greater Number than the generated number")
            print(f"you only had {5-count} chances to solve this problem")
            count+=1
            b = int(input("select your number : "))
print(f"The random number that is generated by the computer is {a}")